---
resource_types:
- name: bosh2-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: v2.8.1

resources:
- name: git
  type: git
  source:
    uri: git@github.com:govau/instant-https-boshrelease.git
    private_key: {{git_private_key}}
    branch: master
    ignore_paths:
    - releases/*
- name: git-push
  type: git
  source:
    uri: git@github.com:govau/instant-https-boshrelease.git
    private_key: {{git_private_key}}
    branch: master
- name: github-release
  type: github-release
  source:
    owner: govau
    repository: instant-https-boshrelease
    access_token: {{git_personal_access_token}}
- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:govau/boshreleases.git
    branch: master
    file: instant-https.version
    initial_version: 0.5.0
    private_key: {{git_boshreleases_private_key}}

jobs:
- name: build-it
  plan:
  - aggregate:
    - get: version
      params:
        bump: minor
    - get: git
      trigger: true

  - task: create-bosh-release
    file: git/ci/create-bosh-release.yml
    params:
      bosh_release_name: instant-https
      access_key_id: {{boshrelease_s3_bucket_access_key_id}}
      secret_access_key: {{boshrelease_s3_bucket_secret_access_key}}

  - put: version
    params:
      file: version/version

  - put: git-push
    params:
      rebase: true
      repository: boshrelease-output
      tag: version/version
      tag_prefix: v

  - put: github-release
    params:
      name: github-release-info/name
      tag: github-release-info/tag
      body: github-release-info/body
      globs:
      - github-release-info/*-*.*.*.tgz
